import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import { cloudflare } from "@cloudflare/vite-plugin";
import { defineConfig } from "vite";

/**
 * Build identity, resolved once per build and inlined by `define`.
 *
 * A build that cannot name itself makes every bug report ambiguous, so the SHA
 * is stamped into the bundle rather than looked up at runtime (a Worker has no
 * git). Outside a git checkout — a source tarball, a container build — the
 * fallback is the honest string `unknown`, never a fabricated version.
 *
 * The stamp is deliberately kept out of the OpenAPI document: the document's
 * digest is a parity gate, and a timestamp inside it would break that gate on
 * every rebuild.
 */
function buildSha(): string {
  const fromEnvironment = process.env.MARQUEE_BUILD_SHA ?? process.env.GITHUB_SHA;
  if (fromEnvironment) return fromEnvironment.slice(0, 12);
  try {
    return execFileSync("git", ["rev-parse", "--short=12", "HEAD"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "unknown";
  }
}

const FRONT_DOOR_INPUTS = [
  resolve(import.meta.dirname, "src/agent-front-door/llms.txt"),
  resolve(import.meta.dirname, "src/agent-front-door/llms-full.txt"),
];
const BOOTSTRAP_MARKER = "# Build bootstrap";

/**
 * The generated raw imports are intentionally ignored. Only scripts/build.mjs
 * may authorize a production build: its first pass supplies bootstrap inputs,
 * and its final pass supplies the generated bytes. This keeps a direct
 * `vite build` from silently shipping a placeholder or a stale local output.
 */
function frontDoorBuildGuard() {
  return {
    name: "marquee-front-door-build-guard",
    configResolved(config: { command: string }) {
      const missing = FRONT_DOOR_INPUTS.filter((path) => !existsSync(path));
      if (config.command === "serve") {
        if (missing.length > 0) {
          throw new Error("front door inputs are absent; run `npm run dev` (or `npm run build`) first");
        }
        return;
      }
      if (config.command !== "build") return;
      const phase = process.env.MARQUEE_FRONT_DOOR_PHASE;
      if (phase !== "bootstrap" && phase !== "final") {
        throw new Error("front door builds must run through `npm run build`");
      }
      if (phase === "final") {
        if (missing.length > 0) throw new Error("final front door build has missing generated inputs");
        if (FRONT_DOOR_INPUTS.some((path) => readFileSync(path, "utf8").includes(BOOTSTRAP_MARKER))) {
          throw new Error("final front door build received bootstrap inputs; run `npm run build`");
        }
      }
    },
  };
}

export default defineConfig({
  define: {
    __MARQUEE_BUILD_SHA__: JSON.stringify(buildSha()),
    __MARQUEE_BUILT_AT__: JSON.stringify(new Date().toISOString()),
  },
  esbuild: {
    jsx: "automatic",
    jsxImportSource: "preact",
  },
  plugins: [frontDoorBuildGuard(), cloudflare()],
  resolve: {
    alias: [
      { find: "react/jsx-dev-runtime", replacement: "preact/jsx-dev-runtime" },
      { find: "react/jsx-runtime", replacement: "preact/jsx-runtime" },
      { find: "react-dom", replacement: "preact/compat" },
      { find: "react", replacement: "preact/compat" },
    ],
  },
});
