#!/usr/bin/env node
/**
 * Seed orchestrator — `npm run seed`.
 *
 * Orchestration only, by contract: this file discovers its sibling seeders by
 * globbing its own directory and verifies the Worker-safe shared manifest.
 * A new per-entity seeder is a new `scripts/seed/<name>.ts` exporting a
 * `SeedModule`, plus one explicit manifest entry so reset and CLI cannot drift.
 * `index.ts` itself and `_*.ts` helpers are excluded.
 *
 * Every seeder appends upsert rows to one shared context. The concatenated SQL
 * is written to a temp file and applied with
 * `wrangler d1 execute DB --local --file …` — the same invocation shape
 * `scripts/schema-verify.mjs` uses. Because every row is an upsert keyed on a
 * deterministic id with deterministic values, re-running converges instead of
 * duplicating, and never deletes: a spine re-run leaves later seeders' data
 * intact. Full wipes belong to `reset:demo`.
 *
 * Flags: `--remote` (apply to the remote D1 instead of local state),
 * `--persist-to <dir>` (local state directory; defaults to wrangler's own, so
 * `wrangler dev` serves the seeded data), `--sql-only` (print the SQL and
 * apply nothing).
 *
 * Runs on plain `node` (>=22.18) via native type stripping. It is a build-time
 * script and is never imported by the Worker.
 */

import { spawnSync } from "node:child_process";
import { mkdtempSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { SeedModule, SeedRow } from "./_sql.ts";
import { upsertStatement } from "./_sql.ts";
// The frozen demo clock is the spine's own constant (SPEC §6); importing it
// keeps one definition rather than duplicating the date in two files.
import { FROZEN_NOW } from "./event.ts";
import { buildDemoSeedRows, DEMO_SEED_MODULES } from "../../src/lib/reset-demo/seed-modules.ts";

const SEED_DIRECTORY = dirname(fileURLToPath(import.meta.url));
const REPOSITORY_ROOT = resolve(SEED_DIRECTORY, "..", "..");
const WRANGLER = join(REPOSITORY_ROOT, "node_modules", ".bin", "wrangler");

const HEADER = [
  "-- Generated by scripts/seed/index.ts — do not edit, do not commit.",
  "-- Every statement is an upsert on a deterministic id, so applying this",
  "-- file twice is a no-op. See SEED-DATA.md for data provenance.",
  "",
].join("\n");

/** Sibling seeders are discovered for parity with the Worker-safe manifest. */
export function discoverSeedFiles(): string[] {
  return readdirSync(SEED_DIRECTORY)
    .filter(
      (name) =>
        name.endsWith(".ts") &&
        !name.endsWith(".d.ts") &&
        name !== "index.ts" &&
        !name.startsWith("_"),
    )
    .sort();
}

export async function loadSeedModules(): Promise<SeedModule[]> {
  const discovered = new Set(
    discoverSeedFiles().map((file) => file.slice(0, -".ts".length)),
  );
  const manifest = new Set(DEMO_SEED_MODULES.map((module) => module.name));
  const missing = [...discovered].filter((name) => !manifest.has(name));
  const stale = [...manifest].filter((name) => !discovered.has(name));
  if (missing.length || stale.length) {
    throw new Error(
      `seed manifest drifted: missing=${missing.sort().join(",") || "none"} stale=${stale.sort().join(",") || "none"}`,
    );
  }
  return [...DEMO_SEED_MODULES];
}

/** Every row every seeder wants, in dependency order. */
export async function buildSeedRows(now: number = FROZEN_NOW): Promise<SeedRow[]> {
  return buildDemoSeedRows(now, await loadSeedModules());
}

export async function buildSeedSql(now: number = FROZEN_NOW): Promise<string> {
  const rows = await buildSeedRows(now);
  return `${HEADER}${rows.map((row) => upsertStatement(row)).join("\n")}\n`;
}

interface SeedOptions {
  remote: boolean;
  persistTo?: string;
  sqlOnly: boolean;
}

export function parseSeedArguments(argv: readonly string[]): SeedOptions {
  const options: SeedOptions = { remote: false, sqlOnly: false };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--remote") options.remote = true;
    else if (argument === "--sql-only") options.sqlOnly = true;
    else if (argument === "--persist-to") {
      const value = argv[index + 1];
      if (!value) throw new Error("--persist-to needs a directory");
      options.persistTo = value;
      index += 1;
    } else if (argument.startsWith("--persist-to=")) {
      options.persistTo = argument.slice("--persist-to=".length);
    } else throw new Error(`unknown seed flag: ${argument}`);
  }
  if (options.remote && options.persistTo) {
    throw new Error("--persist-to only applies to local seeding; drop --remote or --persist-to");
  }
  return options;
}

function summarize(rows: readonly SeedRow[]): string {
  const counts = new Map<string, number>();
  for (const row of rows) counts.set(row.table, (counts.get(row.table) ?? 0) + 1);
  return [...counts]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([table, count]) => `${table}=${count}`)
    .join(" ");
}

async function main(): Promise<void> {
  const options = parseSeedArguments(process.argv.slice(2));
  const rows = await buildSeedRows();
  const sql = `${HEADER}${rows.map((row) => upsertStatement(row)).join("\n")}\n`;

  if (options.sqlOnly) {
    process.stdout.write(sql);
    return;
  }

  const workspace = mkdtempSync(join(tmpdir(), "marquee-seed-"));
  const sqlPath = join(workspace, "seed.sql");
  writeFileSync(sqlPath, sql);

  const wranglerArguments = ["d1", "execute", "DB", options.remote ? "--remote" : "--local"];
  if (options.persistTo) wranglerArguments.push("--persist-to", options.persistTo);
  wranglerArguments.push("--file", sqlPath, "--yes");

  try {
    const result = spawnSync(WRANGLER, wranglerArguments, {
      cwd: REPOSITORY_ROOT,
      stdio: "inherit",
      env: { ...process.env, CI: "1", NO_COLOR: "1" },
    });
    if (result.status !== 0) {
      throw new Error(`wrangler d1 execute failed (exit ${result.status ?? "signal"})`);
    }
  } finally {
    rmSync(workspace, { force: true, recursive: true });
  }

  console.log(`seeded ${rows.length} rows — ${summarize(rows)}`);
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : undefined;
if (invokedPath === fileURLToPath(import.meta.url)) await main();
