#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import { access, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import {
  FULL_OUTPUT_PATH,
  GENERATED_BANNER,
  LLMS_OUTPUT_PATH,
  REPOSITORY_ROOT,
  renderFrontDoor,
  writeFrontDoorOutputs,
} from "./generate-agent-front-door.mjs";

const VITE = resolve(REPOSITORY_ROOT, "node_modules/.bin/vite");

// The first pass only exists to produce the Worker bundle whose served OpenAPI
// response supplies the generated facts. A clean checkout has no generated
// raw imports yet, so give Vite a harmless input until that pass completes.
const BOOTSTRAP_TEXT = `${GENERATED_BANNER}\n# Build bootstrap\n`;

async function ensureBootstrapInput(path) {
  try {
    await access(path);
  } catch {
    await writeFile(path, BOOTSTRAP_TEXT, "utf8");
  }
}

function buildWorker(phase) {
  const result = spawnSync(VITE, ["build"], {
    cwd: REPOSITORY_ROOT,
    stdio: "inherit",
    env: { ...process.env, MARQUEE_FRONT_DOOR_PHASE: phase },
  });
  if (result.status !== 0) throw new Error("build: Vite Worker build failed");
}

await ensureBootstrapInput(LLMS_OUTPUT_PATH);
await ensureBootstrapInput(FULL_OUTPUT_PATH);

// Pass one gives the generator the exact OpenAPI bytes served by the Worker.
buildWorker("bootstrap");
const result = await renderFrontDoor();
await writeFrontDoorOutputs(result);

// Pass two embeds the newly generated bytes in the Worker that deployment will
// serve. The build SHA is stamped by vite.config.ts in this final artifact.
buildWorker("final");
process.stdout.write(`built and generated ${result.manifest.length + 2} front-door documents\n`);
