import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const root = new URL("../../", import.meta.url);
const source = async (path) => readFile(new URL(path, root), "utf8");

test("MRQ-106 · the public agenda keeps a door to its own data feed", async () => {
  // Removed in MRQ-94's navigation repair with nothing put in its place, which
  // left the JSON feed behind the agenda with no on-page entrance at all. It
  // comes back carrying the page's own filters — the unscoped version is what
  // MRQ-94 was right to delete.
  const agenda = await source("src/ui/public/agenda/PublicAgendaPage.tsx");
  assert.match(agenda, /href=\{`\/api\/v1\/public\/agenda\?\$\{feedQuery\.toString\(\)\}`\}>Agenda data ↗<\/a>/);
  assert.match(agenda, /if \(data\.filters\.day && data\.filters\.day !== "all"\) feedQuery\.set\("day", data\.filters\.day\);/);
  assert.match(agenda, /if \(data\.filters\.track\) feedQuery\.set\("track", data\.filters\.track\);/);
  assert.match(agenda, /if \(data\.filters\.q\) feedQuery\.set\("q", data\.filters\.q\);/);
});

test("MRQ-106 · the Ready-to-place escape holds its space before the count arrives", async () => {
  const page = await source("src/ui/submissions/SubmissionsPage.tsx");
  const styles = await source("src/ui/submissions/submissions.css");

  // The escape button is rendered in both states and hidden, never added on
  // arrival — otherwise "Clear filters" slides sideways under the pointer.
  assert.match(page, /class=\{`accepted-escape-action\$\{[^}]*\? " is-ready" : ""\}`\}/);
  assert.match(styles, /\.state-row \.accepted-escape-action \{[^}]*visibility: hidden/);
  assert.match(styles, /\.state-row \.accepted-escape-action\.is-ready \{ visibility: visible; \}/);
  // The note keeps a full line whether or not it has words in it.
  assert.match(styles, /\.state-row \.accepted-escape \{[^}]*min-height: 18px/);
  // The count reads as a number, not as prose.
  assert.match(styles, /\.state-row \.accepted-escape strong \{[^}]*font-variant-numeric: tabular-nums/);

  // The non-empty half: the note above the table reserves its line and its
  // control from the moment the filter is on, so the table never moves.
  assert.match(page, /acceptedStageFilter && !acceptedStageDeadEnd && <div class=\{`accepted-any-note \$\{undercounted \? "visible" : ""\}`\}/);
  assert.match(page, /"Accepted-count space reserved"/);
  assert.match(styles, /\.accepted-any-note \{[^}]*color: transparent[^}]*min-height: 30px/);
  assert.match(styles, /\.accepted-any-note \.button \{ visibility: hidden; \}/);
});

test("MRQ-106 · the route map is generated and gated, never hand-written", async () => {
  const packageJson = JSON.parse(await source("package.json"));
  const gate = await source("scripts/checks/pr-gate.mjs");
  const map = await source("docs/ROUTES.md");

  assert.equal(packageJson.scripts["check:routes"], "node scripts/checks/check-routes.mjs");
  assert.match(gate, /\["route map", "npm", \["run", "check:routes"\]\]/);
  assert.match(map, /GENERATED by `npm run check:routes -- --write`/);
  // The four route claims that shipped false twice. `/site` and
  // `/settings/webhooks` are not routes; `/comms` is `/communications`; and
  // `/agenda` is the public site, not the organizer's builder.
  assert.doesNotMatch(map, /`\/site`/);
  assert.doesNotMatch(map, /`\/settings\/webhooks`/);
  assert.doesNotMatch(map, /`\/comms`/);
  assert.match(map, /`\/communications`/);
  assert.match(map, /`\/agenda-builder`/);
});
