import { expect, test } from "vitest";

import { PUBLIC_SCHEDULE_SCRIPT } from "../../src/ui/public/agenda/schedule-script";

/**
 * The QR encoder is the one piece of this feature that cannot be checked by
 * reading it: a matrix is either scannable or it is not, and both of its bugs
 * on the way here (a transposed format-information strip, and alignment
 * patterns skipped where they cross a timing line) produced codes that looked
 * perfectly QR-shaped and decoded to nothing.
 *
 * So this test pins the output. The golden matrix below was generated by this
 * encoder and then decoded back to "HELLO" by two independent decoders —
 * zbarimg and OpenCV's QRCodeDetector — as were versions 2, 5, 6, 7, 8, 9 and
 * 10 at payload lengths from 30 to 260 bytes. If a change to the encoder moves
 * a single module here, that verification has to be redone rather than the
 * expectation edited.
 */
const HELLO_V1_L = [
  "111111101011101111111",
  "100000100011001000001",
  "101110101101001011101",
  "101110101100101011101",
  "101110101001001011101",
  "100000100111101000001",
  "111111101010101111111",
  "000000000001100000000",
  "111100101111110011101",
  "110101011001111001100",
  "001011100001000000011",
  "110101001101001111010",
  "100111101000100100101",
  "000000001001001000101",
  "111111100001100100000",
  "100000100110000111110",
  "101110100010111111011",
  "101110101101001011110",
  "101110101000101100100",
  "100000101000010110001",
  "111111101100010100000",
];

/** Lift `qrMatrix` out of the browser module so the encoder can be run in Node. */
function loadEncoder(): (text: string) => number[][] | null {
  const source = PUBLIC_SCHEDULE_SCRIPT.slice(
    PUBLIC_SCHEDULE_SCRIPT.indexOf("const QR_EC"),
    PUBLIC_SCHEDULE_SCRIPT.indexOf("function drawQr"),
  );
  expect(source).toContain("function qrMatrix");
  return new Function(`${source}; return qrMatrix;`)() as (text: string) => number[][] | null;
}

const render = (matrix: number[][]): string[] =>
  matrix.map((row) => row.map((cell) => (cell & 1 ? "1" : "0")).join(""));

test("CONTRACT · MRQ-132 the QR encoder reproduces a decoder-verified matrix", () => {
  const qrMatrix = loadEncoder();
  const matrix = qrMatrix("HELLO");
  expect(matrix).not.toBeNull();
  expect(render(matrix!)).toEqual(HELLO_V1_L);
});

test("CONTRACT · MRQ-132 a sync link picks a version that fits, and an impossible payload draws nothing", () => {
  const qrMatrix = loadEncoder();
  const syncUrl = "https://marquee.stage11.dev/agenda?event=aie-nyc-2026&sched=MQ-K7TQM3RAX9TQ2#k=9f2c1ab4d7e05638";
  const matrix = qrMatrix(syncUrl);
  expect(matrix).not.toBeNull();
  // Version 5 (37 modules) is the smallest that holds a 95-byte payload at
  // error-correction level L.
  expect(matrix!.length).toBe(37);
  for (const row of matrix!) expect(row).toHaveLength(37);
  // Finder pattern, top-left corner: the three concentric rings.
  expect(render(matrix!)[0].slice(0, 8)).toBe("11111110");
  expect(render(matrix!)[1].slice(0, 8)).toBe("10000010");
  expect(render(matrix!)[2].slice(0, 8)).toBe("10111010");

  // Beyond version 10 the encoder reports failure instead of drawing a
  // truncated code that scans to the wrong URL.
  expect(qrMatrix("x".repeat(400))).toBeNull();
});
